### ISSUE TITLE
Problème lors du lancement

### ISSUE THREAD

**Issue by naathael** [AkimotoRyou/ModMail#73]
Hello I have a problem when launching the bot:
Uncaught TypeError TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (c:\Users\verno\node_modules\node-fetch\lib\index.js:1327:9)
    at <anonymous> (c:\Users\verno\node_modules\node-fetch\lib\index.js:1440:19)
    at fetch (c:\Users\verno\node_modules\node-fetch\lib\index.js:1437:9)
    at get (c:\Users\verno\node_modules\@replit\database\index.js:20:18)
    at get (c:\Users\verno\Desktop\ModMail-master\functions\DB.js:63:31)
    at execute (c:\Users\verno\Desktop\ModMail-master\functions\dbSync.js:13:35)
    at processTicksAndRejections (internal/process/task_queues:96:5)

I run it from visual studio
PLS help

**Comment by AkimotoRyou** [comment]
Don't use replDB, read the README file for the instructions.
